### ISSUE TITLE
Setup and installation.

### ISSUE THREAD

**Issue by datomnurdin** [GeoMash/nutsNBolts#1]
Is there any setup or installation documentation for this library? Thanks.

**Comment by dmsanter-zz** [comment]
Hi Nurdin,

You can check out the doco at the following site:

http://nnb.geomash.com/

Regards,

{
    "name" : "Damien Santer", "title" : "CEO", "company" : "GeoMash Sdn
Bhd", "reg_no" : "1052605-V",
    "address" : "Level 7, 1 The Boulevard, Mid Valley City, KL, 59200",
    "contacts" : [ { "phone" : "+60 3 2202 3333" }, { "mobile" : "+60 12
932 0899" }, { "email" : "damien.santer@geomash.com" } ],
    "url" : "http://geomash.com", "location" : { "type" : "Point",
"coordinates" : [ 101.675956 , 3.117138 ] }
}

**Comment by datomnurdin** [comment]
Noted with thanks.
